#!/bin/sh

#
#
#	 Custom Gui for Technicolor Modem: utility script and modified gui for the Technicolor Modem
#	 								   interface based on OpenWrt
#
#    Copyright (C) 2018  Christian Marangi <ansuelsmth@gmail.com>
#
#    This file is part of Custom Gui for Technicolor Modem.
#
#    Custom Gui for Technicolor Modem is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Custom Gui for Technicolor Modem is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Custom Gui for Technicolor Modem.  If not, see <http://www.gnu.org/licenses/>.
#
#

LIGHT_RED='\033[1;31m'
NC='\033[0m'

print_logo() {
  echo -e "${LIGHT_RED}

 █████╗ ███╗   ██╗███████╗██╗   ██╗███████╗██╗
██╔══██╗████╗  ██║██╔════╝██║   ██║██╔════╝██║
███████║██╔██╗ ██║███████╗██║   ██║█████╗  ██║
██╔══██║██║╚██╗██║╚════██║██║   ██║██╔══╝  ██║
██║  ██║██║ ╚████║███████║╚██████╔╝███████╗███████╗
╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚══════╝╚══════╝
(Modified Gui UpgradeScript)               (Christo)
${NC}
"
}

curl="/usr/bin/curl -m 300 -k -f -L"
bzcat=/usr/bin/bzcat
tar=/bin/tar
rootdevice_call="debug"

############TRANSFORMER UTILITY##################
set_transformer() {
  cmd="require('datamodel').set('$1','$2')"
  lua -e "$cmd"
}
#################################################

logecho() {
  logger -t "Upgrade Script" "$1"
  echo "Upgrade Script" "$1"
}

if [ "$1" = "SetTime" ]; then
  time="$(uci get -q modgui.gui.autoupgrade_hour)"
  time="${time:-03:00}"
  if echo "$time" | grep -q ":"; then
    hour="$(echo "$time" | cut -d: -f1)"
    minute="$(echo "$time" | cut -d: -f2)"
  else
    hour="$time"
    minute="00"
  fi
  # Format valid numbers
  hour="$(echo "$hour" | sed 's/^0*\([0-9]\)/\1/')"
  minute="$(echo "$minute" | sed 's/^0*\([0-9]\)/\1/')"
  hour="${hour:-3}"
  minute="${minute:-0}"
  autoupgrade="$(uci get -q modgui.gui.autoupgrade)"
  mkdir -p /etc/crontabs
  touch /etc/crontabs/root
  sed -i '/upgradegui/d' /etc/crontabs/root
  if [ "$autoupgrade" = "1" ]; then
    echo "$minute $hour * * * /usr/share/transformer/scripts/upgradegui AutoUpgrade >/dev/null 2>&1" >>/etc/crontabs/root
    /etc/init.d/cron restart >/dev/null 2>&1 || true
  fi
  exit 0
fi

LOCKFILE=/var/run/upgradegui.pid
if [ -f "$LOCKFILE" ]; then
  OLDPID="$(cat "$LOCKFILE" 2>/dev/null)"
  if [ -n "$OLDPID" ] && kill -0 "$OLDPID" 2>/dev/null; then
    logecho "Upgrade process already running (PID: $OLDPID). Aborting duplicate."
    exit 0
  fi
fi
echo $$ > "$LOCKFILE"
trap 'rm -f "$LOCKFILE"' EXIT INT TERM

if [ "$1" ]; then
  if [ "$1" = "AutoUpgrade" ]; then
    /usr/share/transformer/scripts/checkver
    if [ "$(uci get modgui.gui.outdated_ver)" = "0" ]; then
      logecho "Already at latest version. Aborting upgrade."
      exit 0
    fi
    # Enabling alert for the gui about the autoupgrade
    uci set modgui.gui.autoupgradeview=auto
    uci commit modgui
  fi
else
  print_logo
  # Enabling alert for the gui about the manual upgrade
  uci set modgui.gui.autoupgradeview=manual
fi

URL_BASE="https://raw.githubusercontent.com/NobodySan97/gui-dev-build-auto/master"

# Check update_branch
if [ ! "$(uci get -q modgui.gui.update_branch)" ] || [ "$(uci get -q modgui.gui.update_branch)" = "stable" ]; then
  update_branch=""
elif [ "$(uci get -q modgui.gui.update_branch)" = "preview" ]; then
  update_branch="_preview"
else
  update_branch="_dev"
fi

normalize() {
  normalized_version=$1
  if [ "$(echo $1 | grep -E '\.[0-9]\.')" ]; then
    normalized_version="$(echo $1 | sed 's|\.\([0-9]\.\)|.0\1|g')"
  fi
  if [ "$(echo $normalized_version | tail -c 3 | grep "\.")" ]; then
    normalized_version="$(echo "$normalized_version" | sed 's|\(\.[0-9][0-9]\.\)\([0-9]\)|\10\2|g')"
  fi

  echo "$normalized_version"
}

enum() {
  echo "$(echo "$1" | sed -e 's/\.//g')"
}

#Check if stable have a new version

ubus send fwupgrade '{"state":"upgrading"}'

WORKING_DIR="/tmp"
PERMANENT_STORE_DIR="/root"
TARGET_DIR="/"
FILE_NAME='GUI'$update_branch'.tar.bz2'
STABLE_FILE_NAME='GUI.tar.bz2'
CHECKSUM_FILE="version"
FORCE_SAVE_GUI=0

overlay_available_space=$(df /overlay | sed -n 2p | awk {'{print $4}'})
if [ "$overlay_available_space" -lt 3000 ]; then
  logecho "ERROR: not enough space to complete operation" >&2
  #Should probably implement some sort of erase here <kevdagoat>
  ubus send fwupgrade '{"state":"done"}'
  exit 1
fi

if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload is now present

  set_transformer "rpc.system.modgui.executeCommand.state" "Downloading"

  logecho "Downloading GUI file..."
  # Enter /tmp folder
  if ! cd "$WORKING_DIR"; then
    logecho "ERROR: Can't access $WORKING_DIR" >&2
    ubus send fwupgrade '{"state":"done"}'
    exit 1
  fi

  # Clean older GUI archive if present
  rm -f "$WORKING_DIR/$FILE_NAME"* "$WORKING_DIR/GUI"*

  # Download new GUI to /tmp
  if ! $curl -# "$URL_BASE/$FILE_NAME" --output "$WORKING_DIR/$FILE_NAME"; then
    echo ""
    logecho "ERROR: Can't find new GUI file" >&2
    ubus send fwupgrade '{"state":"done"}'
    exit 1
  fi
  echo ""

  # Check GUI hash
  if [ -f /tmp/$CHECKSUM_FILE ]; then
    rm "$WORKING_DIR/$CHECKSUM_FILE"
  fi
  $curl -s "$URL_BASE/$CHECKSUM_FILE" --output "$WORKING_DIR/$CHECKSUM_FILE"

  downloaded_md5="$(md5sum "$WORKING_DIR/$FILE_NAME" | cut -d' ' -f1)"

  if ! grep -q "$downloaded_md5" "$WORKING_DIR/$CHECKSUM_FILE"; then
    rm "$WORKING_DIR/$FILE_NAME"
    rm "$WORKING_DIR/$CHECKSUM_FILE"
    logecho "ERROR: File corrupted!!!" >&2
    logecho "ERROR: Removing upgrade file and aborting." >&2
    #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
    ubus send fwupgrade '{"state":"done"}'
    exit 1
  fi

  logecho "Downloaded GUI with hash: $downloaded_md5"

  if [ "$update_branch" ]; then
    if [ "$update_branch" = "_dev" ] || [ "$update_branch" = "_preview" ]; then

      logecho "Dev branch detected... Checking for newer version in stable..."

      if [ -f "$WORKING_DIR/$STABLE_FILE_NAME" ]; then
        rm "$WORKING_DIR/$STABLE_FILE_NAME"
      fi

      # Download stable GUI to /tmp

      if ! $curl $URL_BASE/$STABLE_FILE_NAME --output $WORKING_DIR/$STABLE_FILE_NAME; then
        logecho "ERROR: Can't find stable GUI file" >&2
        rm "$WORKING_DIR/$FILE_NAME"
        rm "$WORKING_DIR/$CHECKSUM_FILE"
        #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
        ubus send fwupgrade '{"state":"done"}'
        exit 1
      fi

      stable_md5=$(md5sum $WORKING_DIR/$STABLE_FILE_NAME | cut -d' ' -f1)

      if ! grep -q "$stable_md5" "$WORKING_DIR/$CHECKSUM_FILE"; then
        rm "$WORKING_DIR/$FILE_NAME"
        rm "$WORKING_DIR/$STABLE_FILE_NAME"
        rm "$WORKING_DIR/$CHECKSUM_FILE"
        logecho "ERROR: Stable file corrupted!!!" >&2
        logecho "ERROR: Removing upgrade file and aborting." >&2
        #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
        ubus send fwupgrade '{"state":"done"}'
        exit 1
      fi

      logecho "Downloaded stable GUI with hash: $stable_md5"

      stable_version="$(cat $WORKING_DIR/$CHECKSUM_FILE | grep $stable_md5 | cut -d' ' -f2)"
      stable_version_norm="$(normalize $stable_version)"

      logecho "Downloaded Stable version: $stable_version_norm"

      dev_version="$(cat $WORKING_DIR/$CHECKSUM_FILE | grep $downloaded_md5 | cut -d' ' -f2)"
      dev_version_norm="$(normalize $dev_version)"

      logecho "Downloaded $update_branch version: $dev_version_norm"

      if [ "$(enum "$stable_version_norm")" -gt "$(enum "$dev_version_norm")" ]; then
        logecho "Found newer version in stable branch, using it..."
        rm "$WORKING_DIR/$FILE_NAME"
        FILE_NAME="$STABLE_FILE_NAME"
        FORCE_SAVE_GUI=1
      else

        if [ -f $PERMANENT_STORE_DIR/$FILE_NAME ]; then
          saved_stable_md5=$(md5sum $PERMANENT_STORE_DIR/$FILE_NAME | cut -d' ' -f1)

          if [ "$saved_stable_md5" != "$stable_md5" ]; then
            logecho "Permanent package md5 is not same of latest Stable GUI. Replacing..."
            rm "$PERMANENT_STORE_DIR/$FILE_NAME"
            cp "$WORKING_DIR/$STABLE_FILE_NAME" "$PERMANENT_STORE_DIR/"
          fi
        fi

        rm "$WORKING_DIR/$STABLE_FILE_NAME"
      fi
    fi
  fi
else
  logecho "Found file in /tmp dir... doing offline upgrade!"
  #Save gui always as STABLE in offline upgrade as we can't check or download it.
  FORCE_SAVE_GUI=1
fi

set_transformer "rpc.system.modgui.executeCommand.state" "Clearing"

#NOT NEEDED ANYMORE
#logecho "Stopping nginx..."
#/etc/init.d/nginx stop

logecho "Cleaning www dir"
#clean old www dir

for dir in /www/*; do
  if [ "$dir" = "/www/docroot" ]; then
    for subdir in /www/docroot/*; do
      if [ "$subdir" = "/www/docroot/aria" ] ||
        [ "$subdir" = "/www/docroot/transmission" ]; then
        continue
      elif [ "$subdir" = "/www/docroot/ajax" ]; then
        for file in /www/docroot/ajax/*; do
          #We need this file to handle rootdevice log in gui
          if [ "$file" != "/www/docroot/ajax/commandlogread.lua" ]; then
            rm "$file"
          fi
        done
      else
        rm -rf "$subdir"
      fi
    done
  else
    rm -rf "$dir"
  fi
done

set_transformer "rpc.system.modgui.executeCommand.state" "Extracting"

logecho "Extracting GUI files to $TARGET_DIR..."
# Extract new GUI to / using fast tar extraction without slow shell pipe loop
if [ -f "$WORKING_DIR/$FILE_NAME" ]; then
  case "$FILE_NAME" in
    *.tar.gz) zcat "$WORKING_DIR/$FILE_NAME" | tar -C "$TARGET_DIR" -xf - ;;
    *) bzcat "$WORKING_DIR/$FILE_NAME" | tar -C "$TARGET_DIR" -xf - ;;
  esac
fi

#Remove deprecated GUI packages if found in /root
if [ -f /root/GUI_dev.tar.bz2 ]; then
  logecho "Deleting /root/GUI_dev.tar.bz2..."
  rm -f /root/GUI_dev.tar.bz2
fi
if [ -f /root/GUI.tar.gz ]; then
  logecho "Deleting GUI.tar.gz..."
  rm -f /root/GUI.tar.gz
fi

if [ -z "$update_branch" ] || [ "$FORCE_SAVE_GUI" = "1" ]; then
  logecho "Copying file to permanent dir..."
  #Copy GUI file to permanent dir
  if [ -f "$PERMANENT_STORE_DIR/$FILE_NAME" ]; then
    rm -f "$PERMANENT_STORE_DIR/$FILE_NAME"
  fi
  cp "$WORKING_DIR/$FILE_NAME" "$PERMANENT_STORE_DIR/$STABLE_FILE_NAME"
fi

rm -f /root/gui_dev.md5sum

sync

[ -d /rom/www/lua ] && cp -r -n /rom/www/lua/* /www/lua/ 2>/dev/null || true
logecho "Running rootdevice script"
# Run init.d script
set_transformer "rpc.system.modgui.executeCommand.state" "In Progress"
/etc/init.d/rootdevice "$rootdevice_call"
/etc/init.d/do_migrate_overlay preserve_files 2>/dev/null || true

# Explicitly reset outdated state in UCI config via atomic batch
uci -q batch <<EOF
set modgui.gui.outdated_ver='0'
set modgui.gui.new_ver='Unknown'
commit modgui
EOF

if [ -f "$WORKING_DIR/$FILE_NAME" ]; then
  rm -f "$WORKING_DIR/$FILE_NAME"
fi
if [ -f "$WORKING_DIR/$CHECKSUM_FILE" ]; then
  rm -f "$WORKING_DIR/$CHECKSUM_FILE"
fi

ubus send fwupgrade '{"state":"done"}'
logecho "Upgrade Done"
