#!/bin/sh

config_load mmpbx

config_get_bool enabled global enabled 0
[ "$enabled" -eq 0 ] && exit 0

iface0="$(uci -q get mmpbxrvsipnet.@network[0].interface)"
iface1="$(uci -q get mmpbxrvsipnet.@network[1].interface)"

if [ "$ACTION" = "ifup" ]; then
	if [ -n "$iface0" ] && [ "$INTERFACE" = "$iface0" ]; then
		/etc/init.d/mmpbxd reload &
	elif [ -n "$iface1" ] && [ "$INTERFACE" = "$iface1" ]; then
		/etc/init.d/mmpbxd reload &
	fi
fi
