#!/bin/sh

[ "$ACTION" = "ifup" ] || exit 0

config_load wol

config_get_bool enabled config enabled 0
[ "$enabled" -eq 1 ] || exit 0

config_get dest_intf config dest_intf "lan"
[ "$INTERFACE" = "$dest_intf" ] || exit 0

config_get dest_ip config dest_ip

[ -n "$dest_ip" ] && [ -n "$DEVICE" ] && {
    # Replace route and ARP spoofing entry
    ip route replace "${dest_ip}/32" dev "$DEVICE" 2>/dev/null
    ip neigh replace "$dest_ip" lladdr ff:ff:ff:ff:ff:ff nud permanent dev "$DEVICE" 2>/dev/null
}
